server:
  port: 8000
spring:
  datasource:
    url: jdbc:mysql://xxx:3306/xxx?characterEncoding=utf8&useSSL=true
    username: xxx
    password: xxx
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/BOOT-INF/classes/static/images/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${web.upload-path}
msg:
  ifopen: true
  label: 【水盈玉人】
  jg:
      appkey: xxx
      secret: xxx
      smgcodeid: 1
weixin:
  item: syy
  brand: 水盈玉人美容养生
  back: static/images/back1.png
host:
  url: http://syy.iborge.cn:8080
