server:
  port: 80
#server.port=8082
spring:
  datasource:
    url: jdbc:mysql://xxx:3306/goldtest?characterEncoding=utf8&useSSL=true
    username: xxx
    password: xxx
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/BOOT-INF/classes/static/images/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${web.upload-path}
msg:
  ifopen: false
  label: 【金夫人】
  jg:
    appkey: xxx
    secret: xxx
    smgcodeid: 1
weixin:
  item: goldlady
  brand: 金夫人
  back: static/images/back2.png
host:
  url: http://gold.iborge.cn:8080
